import React, { useState, useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import { Code2, ArrowRight, Zap, Trophy, BookOpen } from 'lucide-react';

// Radius of the soft spotlight that reveals the vibrant layer beneath the dark base.
const SPOTLIGHT_R = 260;

/**
 * Renders the vibrant aurora layer and masks it with a soft circular spotlight
 * that follows the (already-smoothed) cursor position. The mask is generated by
 * drawing a radial gradient onto an offscreen canvas, exporting it as a data URL,
 * and applying it as the element's mask-image.
 *
 * cursorX / cursorY are coordinates RELATIVE to the hero section (not the window),
 * because MockForge has a sticky navbar above the hero — window coords would be
 * offset vertically.
 */
function RevealLayer({ cursorX, cursorY }) {
  const canvasRef = useRef(null);
  const revealRef = useRef(null);

  // Size the offscreen canvas to the hero (its DOM parent) on mount + resize.
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return undefined;

    const resize = () => {
      const parent = canvas.parentElement;
      if (!parent) return;
      canvas.width = parent.clientWidth;
      canvas.height = parent.clientHeight;
    };

    resize();
    window.addEventListener('resize', resize);
    return () => window.removeEventListener('resize', resize);
  }, []);

  // Redraw the spotlight mask whenever the cursor moves.
  useEffect(() => {
    const canvas = canvasRef.current;
    const reveal = revealRef.current;
    if (!canvas || !reveal) return;

    const ctx = canvas.getContext('2d');
    ctx.clearRect(0, 0, canvas.width, canvas.height);

    const gradient = ctx.createRadialGradient(cursorX, cursorY, 0, cursorX, cursorY, SPOTLIGHT_R);
    gradient.addColorStop(0, 'rgba(255,255,255,1)');
    gradient.addColorStop(0.4, 'rgba(255,255,255,1)');
    gradient.addColorStop(0.6, 'rgba(255,255,255,0.75)');
    gradient.addColorStop(0.75, 'rgba(255,255,255,0.4)');
    gradient.addColorStop(0.88, 'rgba(255,255,255,0.12)');
    gradient.addColorStop(1, 'rgba(255,255,255,0)');

    ctx.fillStyle = gradient;
    ctx.beginPath();
    ctx.arc(cursorX, cursorY, SPOTLIGHT_R, 0, Math.PI * 2);
    ctx.fill();

    const url = canvas.toDataURL();
    reveal.style.maskImage = `url(${url})`;
    reveal.style.webkitMaskImage = `url(${url})`;
    reveal.style.maskSize = '100% 100%';
    reveal.style.webkitMaskSize = '100% 100%';
  }, [cursorX, cursorY]);

  return (
    <>
      <canvas
        ref={canvasRef}
        className="absolute inset-0 pointer-events-none"
        style={{ display: 'none' }}
      />
      <div
        ref={revealRef}
        className="reveal-vibrant absolute inset-0 z-30 pointer-events-none"
      />
    </>
  );
}

const Landing = () => {
  // Cursor smoothing: raw mouse → eased "smooth" via a per-frame lerp.
  const [cursorPos, setCursorPos] = useState({ x: -999, y: -999 });
  const heroRef = useRef(null);
  const mouse = useRef({ x: -999, y: -999 });
  const smooth = useRef({ x: -999, y: -999 });
  const rafRef = useRef(null);

  useEffect(() => {
    const handleMove = (e) => {
      const hero = heroRef.current;
      if (!hero) return;
      const rect = hero.getBoundingClientRect();
      mouse.current = { x: e.clientX - rect.left, y: e.clientY - rect.top };
    };

    window.addEventListener('mousemove', handleMove);

    const loop = () => {
      const dx = mouse.current.x - smooth.current.x;
      const dy = mouse.current.y - smooth.current.y;
      // Only re-render when the cursor is meaningfully in motion — avoids a
      // perpetual toDataURL on every frame once the spotlight has settled.
      if (Math.abs(dx) > 0.1 || Math.abs(dy) > 0.1) {
        smooth.current.x += dx * 0.1;
        smooth.current.y += dy * 0.1;
        setCursorPos({ x: smooth.current.x, y: smooth.current.y });
      }
      rafRef.current = requestAnimationFrame(loop);
    };
    rafRef.current = requestAnimationFrame(loop);

    return () => {
      window.removeEventListener('mousemove', handleMove);
      cancelAnimationFrame(rafRef.current);
    };
  }, []);

  return (
    <div className="flex flex-col min-h-screen tracking-[-0.02em]">

      {/* ===== HERO SECTION (cursor-spotlight reveal) ===== */}
      <section
        ref={heroRef}
        className="relative w-full overflow-hidden bg-black"
        style={{ minHeight: 'calc(100svh - 72px)' }}
      >
        {/* 1. Dark base layer */}
        <div className="hero-base hero-zoom absolute inset-0 z-10" />

        {/* 2. Vibrant reveal layer, masked by the spotlight */}
        <RevealLayer cursorX={cursorPos.x} cursorY={cursorPos.y} />

        {/* Technical dot-grid over both layers */}
        <div className="hero-grid absolute inset-0 z-40 pointer-events-none" />

        {/* 3. Hero content */}
        <div className="relative z-50 flex flex-col items-center justify-center text-center px-5 h-full min-h-[calc(100svh-72px)] py-20 pointer-events-none">
          {/* Badge */}
          <div className="hero-anim hero-fade inline-flex items-center gap-2 bg-white/10 border border-white/20 backdrop-blur-md text-blue-200 text-sm font-medium px-4 py-1.5 rounded-full mb-8" style={{ animationDelay: '0.1s' }}>
            <Zap className="h-4 w-4" />
            Your personal interview simulator
          </div>

          {/* Headline */}
          <h1 className="text-white leading-[0.95] mb-7">
            <span
              className="hero-anim hero-reveal block font-playfair italic font-normal text-5xl sm:text-7xl md:text-8xl"
              style={{ letterSpacing: '-0.05em', animationDelay: '0.25s' }}
            >
              Forge the skills
            </span>
            <span
              className="hero-anim hero-reveal block font-semibold text-5xl sm:text-7xl md:text-8xl -mt-1"
              style={{ letterSpacing: '-0.06em', animationDelay: '0.42s' }}
            >
              interviews demand
            </span>
          </h1>

          {/* Subheadline */}
          <p className="hero-anim hero-fade text-base sm:text-lg text-white/70 max-w-xl mx-auto mb-10" style={{ animationDelay: '0.6s' }}>
            Real coding rounds in a Monaco editor, sandboxed test-case grading,
            timed sessions, and a live leaderboard. Built for developers serious
            about landing the next role.
          </p>

          {/* CTAs — pointer-events re-enabled on the interactive row */}
          <div className="hero-anim hero-fade flex flex-col sm:flex-row gap-4 justify-center pointer-events-auto" style={{ animationDelay: '0.72s' }}>
            <Link
              to="/register"
              className="inline-flex items-center justify-center gap-2 bg-[#e8702a] hover:bg-[#d2611f] text-white text-sm font-medium px-7 py-3 rounded-full transition-all hover:scale-[1.03] active:scale-95 hover:shadow-lg hover:shadow-[#e8702a]/30"
            >
              Start Practicing
              <ArrowRight className="h-4 w-4" />
            </Link>
            <Link
              to="/login"
              className="inline-flex items-center justify-center gap-2 bg-white/10 hover:bg-white/20 border border-white/20 backdrop-blur-md text-white text-sm font-medium px-7 py-3 rounded-full transition-all"
            >
              Login
            </Link>
          </div>

          {/* Stats Row */}
          <div className="hero-anim hero-fade mt-14 flex flex-col sm:flex-row items-center justify-center gap-6 text-white/60 text-sm" style={{ animationDelay: '0.85s' }}>
            <div className="flex items-center gap-2">
              <BookOpen className="h-4 w-4 text-blue-300" />
              <span>Real Coding Rounds</span>
            </div>
            <span className="hidden sm:block text-white/25">•</span>
            <div className="flex items-center gap-2">
              <Zap className="h-4 w-4 text-blue-300" />
              <span>Timed Sessions</span>
            </div>
            <span className="hidden sm:block text-white/25">•</span>
            <div className="flex items-center gap-2">
              <Trophy className="h-4 w-4 text-blue-300" />
              <span>Live Leaderboard</span>
            </div>
          </div>
        </div>

        {/* Discoverability hint for the spotlight (desktop only) */}
        <div className="hidden md:block hero-anim hero-fade absolute bottom-8 left-1/2 -translate-x-1/2 z-50 text-white/40 text-xs tracking-wide pointer-events-none" style={{ animationDelay: '1.1s' }}>
          ✦ Move your cursor to explore
        </div>
      </section>

      {/* ===== FEATURES SECTION ===== */}
      <section className="bg-white dark:bg-gray-900 py-24 px-4 transition-colors duration-300">
        <div className="max-w-5xl mx-auto">

          {/* Section Header */}
          <div className="text-center mb-16">
            <h2 className="text-3xl sm:text-4xl font-bold text-slate-900 dark:text-white mb-4">
              Everything you need to <span className="font-playfair italic font-medium text-blue-600 dark:text-blue-400">prepare</span>
            </h2>
            <p className="text-slate-500 dark:text-gray-400 max-w-xl mx-auto">
              MockForge gives you the tools, the pressure, and the feedback to
              walk into any interview with confidence.
            </p>
          </div>

          {/* Feature Cards */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-8">

            {/* Card 1 */}
            <div className="bg-slate-50 dark:bg-gray-800 border border-slate-100 dark:border-gray-700 rounded-2xl p-8 hover:shadow-lg transition-shadow duration-300">
              <div className="bg-blue-100 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400 w-12 h-12 rounded-xl flex items-center justify-center mb-5">
                <Code2 className="h-6 w-6" />
              </div>
              <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-3">Real Coding Rounds</h3>
              <p className="text-slate-500 dark:text-gray-400">
                Write code in a Monaco editor and have it graded against real
                test cases in a sandbox — Python, JavaScript, C++, and Java.
              </p>
            </div>

            {/* Card 2 */}
            <div className="bg-slate-50 dark:bg-gray-800 border border-slate-100 dark:border-gray-700 rounded-2xl p-8 hover:shadow-lg transition-shadow duration-300">
              <div className="bg-blue-100 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400 w-12 h-12 rounded-xl flex items-center justify-center mb-5">
                <Zap className="h-6 w-6" />
              </div>
              <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-3">Timed Sessions</h3>
              <p className="text-slate-500 dark:text-gray-400">
                Every interview is timed to simulate real pressure. No pausing,
                no overthinking — just you and the clock.
              </p>
            </div>

            {/* Card 3 */}
            <div className="bg-slate-50 dark:bg-gray-800 border border-slate-100 dark:border-gray-700 rounded-2xl p-8 hover:shadow-lg transition-shadow duration-300">
              <div className="bg-blue-100 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400 w-12 h-12 rounded-xl flex items-center justify-center mb-5">
                <Trophy className="h-6 w-6" />
              </div>
              <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-3">Live Leaderboard</h3>
              <p className="text-slate-500 dark:text-gray-400">
                See how you stack up against other developers in real time. Compete,
                improve, and climb the ranks.
              </p>
            </div>

          </div>
        </div>
      </section>

      {/* ===== HOW IT WORKS SECTION ===== */}
      <section className="bg-slate-50 dark:bg-gray-800 py-24 px-4 transition-colors duration-300">
        <div className="max-w-5xl mx-auto">

          {/* Section Header */}
          <div className="text-center mb-16">
            <h2 className="text-3xl sm:text-4xl font-bold text-slate-900 dark:text-white mb-4">
              How It <span className="font-playfair italic font-medium text-blue-600 dark:text-blue-400">Works</span>
            </h2>
            <p className="text-slate-500 dark:text-gray-400 max-w-xl mx-auto">
              Go from zero to interview-ready in three simple steps.
            </p>
          </div>

          {/* Steps */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-8 relative">

            {/* Step 1 */}
            <div className="flex flex-col items-center text-center relative z-10">
              <div className="w-14 h-14 rounded-full bg-blue-600 text-white text-xl font-bold flex items-center justify-center mb-5 shadow-lg">
                1
              </div>
              <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-3">Create an Account</h3>
              <p className="text-slate-500 dark:text-gray-400">
                Sign up in seconds. No credit card, no fluff. Just create your
                profile and you're ready.
              </p>
            </div>

            {/* Step 2 */}
            <div className="flex flex-col items-center text-center relative z-10">
              <div className="w-14 h-14 rounded-full bg-blue-600 text-white text-xl font-bold flex items-center justify-center mb-5 shadow-lg">
                2
              </div>
              <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-3">Pick a Topic & Start</h3>
              <p className="text-slate-500 dark:text-gray-400">
                Choose your topic — Arrays, DP, Graphs, or OOP. The timer starts
                immediately. Treat it like the real thing.
              </p>
            </div>

            {/* Step 3 */}
            <div className="flex flex-col items-center text-center relative z-10">
              <div className="w-14 h-14 rounded-full bg-blue-600 text-white text-xl font-bold flex items-center justify-center mb-5 shadow-lg">
                3
              </div>
              <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-3">Track Your Progress</h3>
              <p className="text-slate-500 dark:text-gray-400">
                See your score, compare it on the leaderboard, and come back
                tomorrow to beat it. Consistency wins.
              </p>
            </div>

          </div>
        </div>
      </section>

      {/* ===== CTA BANNER ===== */}
      <section className="relative overflow-hidden bg-slate-900 dark:bg-gray-950 py-20 px-4 transition-colors duration-300">
        <div className="hero-grid absolute inset-0 opacity-40 pointer-events-none" />
        <div className="relative max-w-3xl mx-auto text-center">
          <h2 className="text-3xl sm:text-4xl font-bold text-white mb-4">
            Ready to start <span className="font-playfair italic font-medium text-[#e8702a]">forging</span> your skills?
          </h2>
          <p className="text-slate-400 mb-8">
            Join developers who are taking their interview prep seriously.
            Your next offer starts here.
          </p>
          <Link
            to="/register"
            className="inline-flex items-center gap-2 bg-[#e8702a] hover:bg-[#d2611f] text-white font-semibold px-10 py-4 rounded-full text-lg transition-all hover:scale-[1.03] active:scale-95 hover:shadow-lg hover:shadow-[#e8702a]/30"
          >
            Get Started — It's Free
            <ArrowRight className="h-5 w-5" />
          </Link>
        </div>
      </section>

      {/* ===== FOOTER ===== */}
      <footer className="bg-slate-950 text-slate-500 py-8 px-4">
        <div className="max-w-5xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">

          {/* Logo */}
          <div className="flex items-center gap-2 text-white font-bold text-lg">
            <Code2 className="h-5 w-5 text-blue-400" />
            <span className="font-playfair italic">MockForge</span>
          </div>

          {/* Copyright */}
          <p className="text-sm">
            © {new Date().getFullYear()} MockForge. Made with ❤️ by{" "}
            <a
              href="https://www.linkedin.com/in/rudhar-bajaj/"
              target="_blank"
              rel="noopener noreferrer"
              className="hover:text-white hover:drop-shadow-[0_0_8px_rgba(255,255,255,0.8)] transition-all duration-300 font-medium"
            >
              Rudhar Bajaj
            </a>.
          </p>

          {/* Links */}
          <div className="flex gap-6 text-sm">
            <Link to="/login" className="hover:text-white transition-colors">Login</Link>
            <Link to="/register" className="hover:text-white transition-colors">Sign Up</Link>
          </div>

        </div>
      </footer>

    </div>
  );
};

export default Landing;
